name: Build Votigram App on PR to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: tmrwdao-runner
    permissions:
      contents: read
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          node-version: "18" # Adjust the Node.js version as needed
          pnpm-version: "8" # Ensures you're using the right pnpm version

      # Step 3: Install pnpm (if not already installed)
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install

      # Step 5: Build the Vite app
      - name: Build the App
        run: pnpm run build
